[features]
seeds = false

[programs.localnet]
solana_twitter = "3dX1z4kEhVMZmJeEEae2YKXYHVkLeNLmLHcswoWVS1Wo"

[programs.devnet]
solana_twitter = "3dX1z4kEhVMZmJeEEae2YKXYHVkLeNLmLHcswoWVS1Wo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/yihwankim/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"